/**
 * Formulario de swing que deesplega un menu en cual tiene diferentes opciones phacia el trabajador.
 */
package BSnature.Admin.Funciones_Admin;

import BSnature.VentanaSign;
import entidades.Admin;
import entidades.Usuario;
import entidadesDAO.TrabajadorDAO;
import entidadesDAO.conectarBD;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author juanj
 */
public class VerTrabajadores extends javax.swing.JFrame {

    private Admin user;
    
    /**
     * Creates new form VerTrabajadores
     */
    public VerTrabajadores() {
        initComponents();
        settearLista();
    }
    
    public void setUsuario(Usuario user){
        this.user = (Admin) user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        botonAlta = new javax.swing.JButton();
        botonBaja = new javax.swing.JButton();
        BotonCambiarContraseña = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonAlta.setText("Dar de alta");
        botonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltaActionPerformed(evt);
            }
        });

        botonBaja.setText("Dar de baja");
        botonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajaActionPerformed(evt);
            }
        });

        BotonCambiarContraseña.setText("Cambiar Contraseña");
        BotonCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarContraseñaActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar lista");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane2.setViewportView(areaTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(botonActualizar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAlta)
                        .addGap(112, 112, 112)
                        .addComponent(botonBaja)
                        .addGap(105, 105, 105)
                        .addComponent(BotonCambiarContraseña)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAlta)
                    .addComponent(botonBaja)
                    .addComponent(BotonCambiarContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(botonActualizar)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltaActionPerformed
        VentanaDarAlta ventanaAlta = new VentanaDarAlta();
        ventanaAlta.setVisible(true);
        ventanaAlta.toFront();
        ventanaAlta.setUsuario(user);
        this.dispose();
    }//GEN-LAST:event_botonAltaActionPerformed

    private void botonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajaActionPerformed
       int filas = 0;
       try{
        String usuario = JOptionPane.showInputDialog(this, "Introduce aqui el nombre del usuario:").trim();
        if(usuario == null){
            JOptionPane.showMessageDialog(this, "El usuario no puede estar vacio", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
                TrabajadorDAO t1 = new TrabajadorDAO();
                filas = t1.eliminarTrabajador(usuario);
        }
       }catch(NullPointerException e){}
        JDialog dialog = new JDialog();
        dialog.setTitle("Eliminacion");
        dialog.setSize(200, 175);
        dialog.setLayout(new FlowLayout());
        dialog.add(new JLabel("Han sido eliminadas " +  filas + " filas"));
        dialog.setVisible(true);
        dialog.toFront();
    }//GEN-LAST:event_botonBajaActionPerformed

    private void BotonCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarContraseñaActionPerformed
        int filas = 0;
        try{
            String usuario = JOptionPane.showInputDialog(this, "Introduce aqui el nombre del usuario:").trim();
        String contraseña = JOptionPane.showInputDialog(this, "Introduce la contrseña nueva:").trim();
        if(usuario != null && contraseña != null){
            try{
                Connection conn = conectarBD.conectarBD();
                String sql = "UPDATE TRABAJADOR SET CONTRASEÑA = ? WHERE USUARIO = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, contraseña);
                stmt.setString(2, usuario);
                filas = stmt.executeUpdate();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Ha habido un error en el sistema", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            JDialog dialog = new JDialog();
            dialog.setTitle("Actualizacion");
            dialog.setSize(200, 175);
            dialog.setLayout(new FlowLayout());
            dialog.add(new JLabel("Han sido actualizadas " +  filas + " contraseñas"));
            dialog.setVisible(true);
            dialog.toFront();
        }
        }catch(NullPointerException e){}
    }//GEN-LAST:event_BotonCambiarContraseñaActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        settearLista();
    }//GEN-LAST:event_botonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCambiarContraseña;
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAlta;
    private javax.swing.JButton botonBaja;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void settearLista() {
       try{
           Connection conn = conectarBD.conectarBD();
           String sql = "SELECT * FROM TRABAJADOR WHERE ES_ADMIN = 0 AND ES_ACTIVO = 1";
           PreparedStatement stmt = conn.prepareStatement(sql);
           ResultSet rs = stmt.executeQuery();
           areaTexto.setText("");
           while(rs.next()){
               String res = rs.getString("NOMBRE") + ", usuario: " + rs.getString("USUARIO") + ", contratado el " + rs.getDate("FECHA_CONTRATACION");
               areaTexto.setText(areaTexto.getText() + "\n" + res);
           }
       }catch(SQLException e){
           System.out.println(e.getMessage());
       }
    }
}
