/**
 * Formulario de swing que abre la ventana principal hacia el menu del cliente
 */
package BSnature.Cliente;

import entidades.Cliente;
import entidades.Usuario;
import entidadesDAO.MascotaDAO;
import entidadesDAO.conectarBD;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author juanj
 */
public class VentanaCliente extends javax.swing.JFrame {

    Cliente user;
    
    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente() {
        initComponents();
    }
    
    public void setUsuario(Usuario user){
        this.user = (Cliente) user;
        labelInicio.setText("Bienvenido a la aplicacion, " + user.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelInicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        botonAdoptar = new javax.swing.JButton();
        botonCeder = new javax.swing.JButton();
        BotonVer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonPerros = new javax.swing.JButton();
        botonGatos = new javax.swing.JButton();
        botonConejos = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("BSNature");

        labelInicio.setText("jLabel2");

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        botonAdoptar.setText("Coger adopcion");
        botonAdoptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdoptarActionPerformed(evt);
            }
        });

        botonCeder.setText("Dar adopcion");
        botonCeder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCederActionPerformed(evt);
            }
        });

        BotonVer.setText("Ver Mascotas");
        BotonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtros:");

        botonPerros.setText("Perros");
        botonPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPerrosActionPerformed(evt);
            }
        });

        botonGatos.setText("Gatos");
        botonGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGatosActionPerformed(evt);
            }
        });

        botonConejos.setText("Conejos");
        botonConejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConejosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(botonAdoptar)
                        .addGap(73, 73, 73)
                        .addComponent(BotonVer)
                        .addGap(73, 73, 73)
                        .addComponent(botonCeder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonPerros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonGatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonConejos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelInicio)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(labelInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCeder)
                    .addComponent(botonAdoptar)
                    .addComponent(BotonVer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(botonPerros)
                    .addComponent(botonGatos)
                    .addComponent(botonConejos))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerActionPerformed
        try{
            Connection conn = conectarBD.conectarBD();
            String sql = "SELECT * FROM MASCOTA WHERE ADOPTADA = 0";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            areaTexto.setText("");
            while(rs.next()){
                areaTexto.setText(areaTexto.getText() + "\n" + rs.getString("NUMERO_MICROCHIP") + ", llamado " + rs.getString("NOMBRE") + ", nacido el " + rs.getDate("FECHA_NACIMIENTO"));
            }
        }catch(SQLException e){
                        System.out.println(e.getMessage());
        }
        botonAdoptar.setEnabled(true);
        botonCeder.setEnabled(true);
    }//GEN-LAST:event_BotonVerActionPerformed

    private void botonAdoptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdoptarActionPerformed
        String fichero_text = "";
        try{  
            String microchip = (JOptionPane.showInputDialog("Introduce aqui el microchip del animal que quieres adoptar"));
            if(microchip.length() == 15){
                MascotaDAO m1 = new MascotaDAO();
                fichero_text = m1.insertAdopcion(user, microchip);
                int input = JOptionPane.showConfirmDialog(this, "Quieres imprimer el trato en un fichero", "CONFIRMATION", JOptionPane.YES_NO_OPTION);
                if(input == 0){
                    try {
                        FileWriter fich = new FileWriter(new File("trato_de_adopcion_" + microchip + ".txt"));
                        fich.write(fichero_text);
                        fich.close();
                    } catch (IOException ex) {
                        System.out.println(ex.getMessage());
                    }
                    }
            }else{
                JOptionPane.showMessageDialog(this, "Has superado la cantidad de caracterers", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }catch(NullPointerException e){}
        botonAdoptar.setEnabled(false);
        botonCeder.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Vuelve a recargar la lista con el boton Ver Mascotas", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonAdoptarActionPerformed

    private void botonCederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCederActionPerformed
        DarAdopcion ventana = new DarAdopcion();
        ventana.setVisible(true);
        ventana.toFront();
        botonAdoptar.setEnabled(false);
        botonCeder.setEnabled(false);
    }//GEN-LAST:event_botonCederActionPerformed

    private void botonPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPerrosActionPerformed
        try{
            Connection conn = conectarBD.conectarBD();
            String sql = "SELECT * FROM MASCOTA WHERE ADOPTADA = 0 AND ID_ESPECIE = 1";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            areaTexto.setText("");
            while(rs.next()){
                areaTexto.setText(areaTexto.getText() + "\n" + rs.getString("NUMERO_MICROCHIP") + ", llamado " + rs.getString("NOMBRE") + ", nacido el " + rs.getDate("FECHA_NACIMIENTO"));
            }
        }catch(SQLException e){
                        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_botonPerrosActionPerformed

    private void botonGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGatosActionPerformed
        try{
            Connection conn = conectarBD.conectarBD();
            String sql = "SELECT * FROM MASCOTA WHERE ADOPTADA = 0 AND ID_ESPECIE = 2";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            areaTexto.setText("");
            while(rs.next()){
                areaTexto.setText(areaTexto.getText() + "\n" + rs.getString("NUMERO_MICROCHIP") + ", llamado " + rs.getString("NOMBRE") + ", nacido el " + rs.getDate("FECHA_NACIMIENTO"));
            }
        }catch(SQLException e){
                        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_botonGatosActionPerformed

    private void botonConejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConejosActionPerformed
        try{
            Connection conn = conectarBD.conectarBD();
            String sql = "SELECT * FROM MASCOTA WHERE ADOPTADA = 0 AND ID_ESPECIE = 3";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            areaTexto.setText("");
            while(rs.next()){
                areaTexto.setText(areaTexto.getText() + "\n" + rs.getString("NUMERO_MICROCHIP") + ", llamado " + rs.getString("NOMBRE") + ", nacido el " + rs.getDate("FECHA_NACIMIENTO"));
            }
        }catch(SQLException e){
                        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_botonConejosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVer;
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton botonAdoptar;
    private javax.swing.JButton botonCeder;
    private javax.swing.JButton botonConejos;
    private javax.swing.JButton botonGatos;
    private javax.swing.JButton botonPerros;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInicio;
    // End of variables declaration//GEN-END:variables
}
