DROP TRIGGER trg_especie_autoincrement;
DROP TRIGGER trg_trato_autoincrement;
DROP TRIGGER trg_tipo_trato_autoincrement;

DROP TABLE Trato CASCADE CONSTRAINTS;
DROP TABLE Cliente_posee_Mascota CASCADE CONSTRAINTS;
DROP TABLE Mascota CASCADE CONSTRAINTS;
DROP TABLE Tipo_Trato CASCADE CONSTRAINTS;
DROP TABLE Especie CASCADE CONSTRAINTS;
DROP TABLE Cliente CASCADE CONSTRAINTS;
DROP TABLE Trabajador CASCADE CONSTRAINTS;

DROP SEQUENCE seq_especie;
DROP SEQUENCE seq_trato;
DROP SEQUENCE seq_tipo_trato;
