/**
 * Formulario de swing que abre la ventana main del proyecto en el cual te logeas.
 */
package BSnature;

import BSnature.Admin.VentanaAdmin;
import BSnature.Cliente.VentanaCliente;
import BSnature.Trabajador.VentanaTrabajador;
import entidades.*;
import entidadesDAO.conectarBD;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author juanj
 */
public class VentanaLogin extends javax.swing.JFrame {

    VentanaSign ventanaSign;
    VentanaCliente ventanaCliente;
    VentanaAdmin ventanaAdmin;
    VentanaTrabajador ventanaTrabajador;
    
    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        textError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonRegistro = new javax.swing.JButton();
        botonInicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textError = new javax.swing.JTextArea();
        fieldContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BSNature");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Inicie Secion aqui:");

        fieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña");

        jLabel5.setText("¿No estas logeado? ");

        botonRegistro.setText("Registrate");
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });

        botonInicio.setText("Iniciar Sesion");
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });

        textError.setColumns(20);
        textError.setRows(5);
        textError.setBorder(null);
        jScrollPane1.setViewportView(textError);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonInicio)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(botonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)))
                                .addGap(145, 145, 145)))
                        .addComponent(fieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(botonInicio)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        ventanaSign = new VentanaSign();
        ventanaSign.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        Usuario usuario_class = null;
        
        String usuario = fieldUsuario.getText().trim();
        String contraseña = new String(fieldContraseña.getPassword()).trim();
        String nombre = "";
        String usuario2 = "";
        String contraseña2 = "";
        String telf = null;
        Date fecha_contratacion = null;
        boolean encontrado = false;
        //Encontrar usuario
        try{
            Connection conn = conectarBD.conectarBD();
            PreparedStatement stmt = conn.prepareStatement("SELECT USUARIO, CONTRASEÑA, NOMBRE, TELF FROM CLIENTE WHERE USUARIO = ? AND CONTRASEÑA = ?");
            stmt.setString(1, usuario);
            stmt.setString(2, contraseña);
            ResultSet rs = stmt.executeQuery();
            while(rs.next()){
                 System.out.println("bucle");
                usuario2 = rs.getString("USUARIO");
                contraseña2 = rs.getString("CONTRASEÑA");
                nombre = rs.getString("NOMBRE");
                telf = rs.getString("TELF");
                encontrado = true;
            }
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
        if(!encontrado){
            //Encontrar trabajador
            int usuario_Admin = 0;
            Integer es_activo = null;
            try{
            Connection conn = conectarBD.conectarBD();
            PreparedStatement stmt = conn.prepareStatement("SELECT USUARIO, CONTRASEÑA, NOMBRE, FECHA_CONTRATACION, ES_ADMIN, ES_ACTIVO FROM TRABAJADOR WHERE USUARIO = ? AND CONTRASEÑA = ?");
            stmt.setString(1, usuario);
            stmt.setString(2, contraseña);
            ResultSet rs = stmt.executeQuery();
            while(rs.next()){
                usuario2 = rs.getString("USUARIO");
                contraseña2 = rs.getString("CONTRASEÑA");
                nombre = rs.getString("NOMBRE");
                fecha_contratacion = rs.getDate("FECHA_CONTRATACION");
                usuario_Admin = rs.getInt("ES_ADMIN");
                es_activo = rs.getInt("ES_ACTIVO");
                encontrado = true;
            }
            if(usuario.equals(usuario2) && contraseña.equals(contraseña2) && es_activo == 1){
                if(usuario_Admin == 0){
                    usuario_class = new Trabajador(usuario, nombre);
                }else{
                    usuario_class = new Admin(usuario, nombre);
                }
            }else{
                textError.setVisible(true);
                textError.setText("El usuario o la contraseña son incorrectas,\npor favor pruebe otra vez\n"
                        + "Verifique que esta registrado en la aplicacion.");
                fieldContraseña.setText("");
            }
        }catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }catch(NullPointerException e){
                System.out.println(e.getMessage());
        }
        }else{
            System.out.println(encontrado + " en el condicionañ");
            if(usuario.equals(usuario2) && contraseña.equals(contraseña2)){
               usuario_class = new Cliente(usuario, nombre);
            }else{
                textError.setVisible(true);
                textError.setText("El usuario o la contraseña son incorrectas,\npor favor pruebe otra vez\n"
                        + "Verifique que esta registrado en la aplicacion.");
                 fieldContraseña.setText("");
            }
        }
        if(encontrado){
        abrirVentana(usuario_class);
        }
    }//GEN-LAST:event_botonInicioActionPerformed

    private void abrirVentana(Usuario user){
        System.out.println("en la funcion");

        if (user instanceof Cliente) {
            ventanaCliente = new VentanaCliente();
            ventanaCliente.setVisible(true);
            ventanaCliente.setUsuario(user);
            System.out.println("entrado");
            this.dispose();
        } else if (user instanceof Trabajador) {
            ventanaTrabajador = new VentanaTrabajador();
            ventanaTrabajador.setUsuario(user);
            ventanaTrabajador.setVisible(true);
            this.dispose();
        } else if (user instanceof Admin) {
            ventanaAdmin = new VentanaAdmin();
            ventanaAdmin.setVisible(true);
            ventanaAdmin.setUsuario(user);
            this.dispose();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JPasswordField fieldContraseña;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textError;
    // End of variables declaration//GEN-END:variables
}
